name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!

    - shell: bash
      run: |
        echo "testing not yet implemented"
        out1=`ls -al`
        out2=`uptime`
        echo "$out1 $out2"

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
